module.exports = [
	"Lost in a ball bit",
	"Free Willy",
	"Arseless chaps",
	"Sex bomb",
	"Drooling your sleep",
	"Haunted Oven",
	"DIY lobotomy",
	"LARPing",
	"The never-ending poo",
	"Sexting",
	"Netflix and chill",
	"Happy slap",
	"Touchy-feely geography teacher",
	"Wiping the smile off your face",
	"Freak show",
	"Love handles",
	"Playing the drums with bananas",
	"Going batshit crazy",
	"Lost in IKEA",
	"Living in a skip",
	"Rubbernecking",
	"Fighting fire with fire",
	"Holding in Hell",
	"Exploding cuckoo clock",
	"Wet handshake",
	"Terrified by butter",
	"Glued to the screen",
	"Mr. Floppy",
	"Foam party",
	"Babe magnet",
	"Tramp stamp",
	"Face-plant",
	"Freezing your own head",
	"Cow tipping",
	"Seeing a man about a horse",
	"Really ugly baby",
	"Christmas dildo",
	"Cereal killer",
	"Ginger Lickin' Good!",
	"A bizarre gardening accident",
	"Running away from your problems",
	"Falling apart",
	"\"Kitten Mittens\"",
	"Dutch oven",
	"Skeleton in your closet",
	"Making an onion cry",
	"Some slight chafing",
	"Anal bleaching",
	"Cannibal finger buffet",
	"Pulling a hat out of a rabbit",
	"Flesh Light",
	"Wandering hands",
	"You scratch my back, I'll scratch yours",
	"Photocopying your balls",
	"Man spreading",
	"Putting make-up on an owl",
	"Crying on the inside",
	"Wheelbarrow race",
	"Licking people's shoes",
]