module.exports = [
	"A happy ending",
	"A little slap and tickle",
	"A poopy penis",
	"Affair with the milkman",
	"Alcoholic house husband",
	"An ambitious reach around",
	"Anal bleaching",
	"Armpit fetish",
	"Arseless chaps",
	"Autoerotic asphyxiation",
	"Babe magnet",
	"Banana hammock",
	"Bangkok Ping Pong Show",
	"Bearded Clam",
	"Big bag of big dicks",
	"Blowing smoke up someone's arse",
	"Bondage gone wrong",
	"Booty call",
	"Botched boob job",
	"Breakfast smegma",
	"Bukkake celebration day",
	"Bum bongos",
	"Burger nips",
	"Carpet matches the drapes",
	"Casting couch",
	"Cat orgy",
	"Chastity belt for birds",
	"Christmas dildo",
	"Constipation",
	"Cooking your man meat",
	"Cream pie",
	"DIY lobotomy",
	"Death's stag do",
	"Deep throat",
	"Disabled streaking",
	"Dogging behind a school",
	"Donkey punch",
	"Donut cock ring",
	"Dragon enema",
	"Drifting into the vagina",
	"Drinking bleach but you're fine",
	"Drive by on a nursery",
	"Drowning a fish in water",
	"Dry humping",
	"Duck high on mushrooms",
	"Ear sex",
	"Edible panties",
	"Erotic oven mitts",
	"Extreme breastfeeding",
	"Eye fucking",
	"Fake taxi",
	"Fisting the Pope",
	"Flesh Light",
	"Free Willy",
	"Friendly camel toe",
	"Frodo and Gandalf at the strip club",
	"Fucking your way out of prison",
	"Getting fingered by the law",
	"Giving birth to a ghost",
	"Glory hole surprise",
	"Going at it like rabbits",
	"Going batshit crazy",
	"Gold digger",
	"Happy slap",
	"Helicopter blade vasectomy",
	"Hitler on vacation",
	"Hitler pegging a seal",
	"Hopelessly trying to find the clitoris",
	"Ian Watkins",
	"Joyless sex",
	"Junk in the trunk",
	"Just the tip",
	"KKK at KFC",
	"Kicking dicks",
	"Lobotomy gone sexual",
	"Love handles",
	"Mail order bride",
	"Man spreading",
	"Manscaping",
	"Mile-high club",
	"Mind sex",
	"Moist",
	"Moobs",
	"Mopping up the jizz",
	"Naked ice fishing",
	"Naked in a lift",
	"Naked statue of yourself",
	"Nazi bar mitzvah",
	"Netflix and chill",
	"Never ending anal-beads",
	"Nudist funeral",
	"Packing a sausage",
	"Pegging Hitler",
	"Photocopying your balls",
	"Pinnocchio the porn star",
	"Playing snooker with your testicles",
	"Polishing a turd",
	"Polite war crimes",
	"Pooing in a urinal",
	"Pooing on a pigeon",
	"Presidential Lap dance",
	"Public masturbation",
	"Putting out a cigarette on your own face",
	"Putting out the fire with your jizz",
	"Queef",
	"Racist grandma",
	"Raining dildos",
	"Rim jobbing the elderly",
	"Road head",
	"Rolling your eyes out of their sockets",
	"S.T.D. appreciation day",
	"Scaring yourself shitless",
	"Scat on a plane",
	"Sex bomb",
	"Sexting",
	"Shooting blanks",
	"Shrek porn",
	"Side boob",
	"Skiing orgy",
	"Sloppy seconds",
	"Snake for a dick",
	"Some slight chafing",
	"Surprise anal",
	"Swedish penis pump",
	"Talking shit",
	"Tentacle handshake",
	"The never-ending poo",
	"The sloppiest of blowjobs",
	"The sweet release of death",
	"Tinder creep",
	"Toaster in the bathtub",
	"Too much viagra",
	"Touching cloth",
	"Touchy-feely geography teacher",
	"Tramp stamp",
	"Trojan cock",
	"Two girls one cup",
	"Up shit creek without a paddle",
	"Vomiting on your grandmother",
	"Vore",
	"Wank bank",
	"Yeast infection",
	"Yiff",
	"Yoghurt stain",
]