module.exports = [
	"1950's Sex Ed poster",
	"A happy ending",
	"A little slap and tickle",
	"Affair with the milkman",
	"Alcoholic house husband",
	"An ambitious reach around",
	"Anal bleaching",
	"Armpit fetish",
	"Arseless chaps",
	"Autoerotic asphyxiation",
	"Babe magnet",
	"Banana hammock",
	"Bangkok Ping Pong Show",
	"Bearded Clam",
	"Big bag of big dicks",
	"Blowing smoke up someone's arse",
	"Bondage gone wrong",
	"Booty call",
	"Botched boob job",
	"Bukkake celebration day",
	"Bum bongos",
	"Burger nips",
	"Carpet matches the drapes",
	"Casting couch",
	"Cat orgy",
	"Christmas dildo",
	"Coat hanger abortion",
	"Constipation",
	"Cream pie",
	"DIY lobotomy",
	"Deep throat",
	"Disabled streaking",
	"Dogging behind a school",
	"Donkey punch",
	"Dragon enema",
	"Dry humping",
	"Ear sex",
	"Edible panties",
	"Erotic oven mitts",
	"Extreme breastfeeding",
	"Fake taxi",
	"Flesh Light",
	"Free Willy",
	"Friendly camel toe",
	"Getting fingered by the law",
	"Glory hole surprise",
	"Going at it like rabbits",
	"Going batshit crazy",
	"Gold digger",
	"Happy slap",
	"Helicopter blade vasectomy",
	"Hitler on vacation",
	"Ian Watkins",
	"Joyless sex",
	"Junk in the trunk",
	"Just the tip",
	"KKK at KFC",
	"Kicking dicks",
	"Love handles",
	"Mail order bride",
	"Man spreading",
	"Manscaping",
	"Mile-high club",
	"Moist",
	"Moobs",
	"Mopping up the jizz",
	"Naked ice fishing",
	"Naked in a lift",
	"Naked statue of yourself",
	"Nazi bar mitzvah",
	"Netflix and chill",
	"Nudist funeral",
	"Packing a sausage",
	"Pegging Hitler",
	"Photocopying your balls",
	"Pinnocchio the porn star",
	"Polishing a turd",
	"Polite war crimes",
	"Pooing in a urinal",
	"Pooing on a pigeon",
	"Presidential Lap dance",
	"Public masturbation",
	"Putting out the fire with your jizz",
	"Queef",
	"Racist grandma",
	"Rim jobbing the elderly",
	"Road head",
	"S.T.D. appreciation day",
	"Scaring yourself shitless",
	"Scat on a plane",
	"Sex bomb",
	"Sexting",
	"Shooting blanks",
	"Shrek porn",
	"Side boob",
	"Sloppy seconds",
	"Some slight chafing",
	"Surprise anal",
	"Swedish penis pump",
	"Talking shit",
	"The never-ending poo",
	"Tinder creep",
	"Too much viagra",
	"Touching cloth",
	"Touchy-feely geography teacher",
	"Tramp stamp",
	"Trojan cock",
	"Two girls one cup",
	"Up shit creek without a paddle",
	"Vore",
	"Wank bank",
	"Yeast infection",
	"Yiff",
	"Yoghurt stain",
]