module.exports = [
	"1950's Sex Ed poster",
	"A happy ending",
	"A little slap and tickle",
	"An ambitious reach around",
	"Anal bleaching",
	"Armpit fetish",
	"Arseless chaps",
	"Babe magnet",
	"Bangkok Ping Pong Show",
	"Big bag of big dicks",
	"Blowing smoke up someone's arse",
	"Booty call",
	"Bukkake celebration day",
	"Bum bongos",
	"Burger nips",
	"Carpet matches the drapes",
	"Casting couch",
	"Christmas dildo",
	"Coat hanger abortion",
	"Constipation",
	"Cream pie",
	"DIY lobotomy",
	"Deep throat",
	"Disabled streaking",
	"Dogging behind a school",
	"Donkey punch",
	"Dragon enema",
	"Dry humping",
	"Ear sex",
	"Edible panties",
	"Erotic oven mitts",
	"Extreme breastfeeding",
	"Fake taxi",
	"Flesh Light",
	"Free Willy",
	"Friendly camel toe",
	"Getting fingered by the law",
	"Glory hole surprise",
	"Going at it like rabbits",
	"Gold digger",
	"Happy slap",
	"Hitler on vacation",
	"Ian Watkins",
	"Joyless sex",
	"Junk in the trunk",
	"Just the tip",
	"Kicking dicks",
	"Love handles",
	"Mail order bride",
	"Man spreading",
	"Mangina",
	"Manscaping",
	"Mile-high club",
	"Moist",
	"Moobs",
	"Mopping up the jizz",
	"Naked ice fishing",
	"Naked in a lift",
	"Netflix and chill",
	"Nudist funeral",
	"Packing a sausage",
	"Photocopying your balls",
	"Pinnocchio the porn star",
	"Polishing a turd",
	"Polite war crimes",
	"Presidential Lap dance",
	"Public masturbation",
	"Queef",
	"Racist grandma",
	"Rim jobbing the elderly",
	"Road head",
	"S.T.D. appreciation day",
	"Sex bomb",
	"Sexting",
	"Shooting blanks",
	"Side boob",
	"Sloppy seconds",
	"Some slight chafing",
	"Surprise anal",
	"Talking shit",
	"Tinder creep",
	"Touching cloth",
	"Touchy-feely geography teacher",
	"Tramp stamp",
	"Two girls one cup",
	"Vore",
	"Yeast infection",
	"Yiff",
]