module.exports = [
	"Laughing your head off",
	"Gastric band",
	"A little slap and tickle",
	"The world's biggest sneeze",
	"Darth Vader's day job",
	"Forgetting how to eat",
	"An ambitious reach around",
	"Touching cloth",
	"Cheese nightmare",
	"Glory hole surprise",
	"Drowning in someone's eye",
	"Kicking dicks",
	"Constipation",
	"Awkward family photo",
	"Neckbeard",
	"A loving pat on the head",
	"Butt dial",
	"Pinnocchio the porn star",
	"Awkward hug",
	"Pooing in a urinal",
	"The duck face",
	"Cleaning out your pipes",
	"Potty mouth",
	"Karate chopping a frog",
	"The Incredible Bouncing Boy™",
	"Builders breaking",
	"Bingo wings",
	"Mail order bride",
	"The Heimlich maneuver",
	"Naked in a lift",
	"Up shit creek without a paddle",
	"Riding a weasel",
	"Blowing smoke up someone's arse",
	"Shotgun wedding",
	"Tinder creep",
	"Florida Man",
	"Bad babysitter",
	"Tasering a sloth",
	"Talking shit",
	"Fainting goats",
	"Throwing the baby out with the bathwater",
	"Erotic oven mitts",
	"Cat orgy",
	"Sausage fingers",
	"Scaring yourself shitless",
	"Angry barbecue",
	"Mangina",
	"Giraffe limbo contest",
	"Pooing on a pigeon",
	"Making an arse out of yourself",
	"Burger nips",
	"Death  by salmon",
	"Velociraptor Jesus",
	"Trust exercises",
	"Dancing on someone's grave",
	"Jazz hands",
	"Bunny boiler",
	"Your vegetable friend",
	"Cowboy wrestling",
	"Self-portrait (you, in the morning)",
]