module.exports = [
	"100 red balloons",
	"12 Bongo cats",
	"A Jackson Pollock painting",
	"A Lemon sinking into the Ocean",
	"A Police man, a horse, and a duck walk into a bar",
	"A bad haircut",
	"A bizarre gardening accident",
	"A building that looks like a spoon",
	"A loving pat on the head",
	"A man hiding in a pram",
	"A sword shaped butter knife",
	"A very disappointing Christmas",
	"Abducted by butterflies",
	"Adopting a cacus",
	"Amoeba disco",
	"An idiot sandwich",
	"An unfortunate birthmark",
	"Angry barbecue",
	"Annoyed swan",
	"Astronaut eating rice",
	"Awkward family photo",
	"Awkward hug",
	"Aztec sacrifice",
	"Baby Harry Potter with a gun",
	"Baby pomeranian loves you",
	"Back acne",
	"Bad babysitter",
	"Badly drawn on eyebrows",
	"Badly trained dentist",
	"Bald eagle on a roller coaster",
	"Balsamic vinegar addiction",
	"Banana eating a banana",
	"Bank heist gone wrong",
	"Barney eats the Earth",
	"Beating around the bush",
	"Beating up a jellyfish",
	"Beer goggles",
	"Big girl's blouse",
	"Bingo wings",
	"Biting off more than you can chew",
	"Brain freeze",
	"Brushing your tongue",
	"Bunny boiler",
	"Bunny staying hydrated",
	"Butt chin",
	"Butt dial",
	"Cannibal finger buffet",
	"Capsizing ship",
	"Cat got you tongue",
	"Cat holding a rocket surgeon",
	"Cat with 8 legs",
	"Centaur lolipop man",
	"Cereal killer",
	"Cheese nightmare",
	"Choking on doughnuts",
	"Christmas in July",
	"City on a whale",
	"Cleaning out your pipes",
	"Clown police line-up",
	"Colossal coconut",
	"Combing your hair with hedgehog",
	"Communist Pokemon",
	"Cool guy walking away from explosion",
	"Costing an arm and a leg",
	"Cow tipping",
	"Cowboy Gremlin",
	"Cowboy wrestling",
	"Crap parkour",
	"Crocodile as a chef",
	"Crying on the inside",
	"Crying over spilt milk",
	"Crying yourself to sleep",
	"Dad dancing",
	"Dancing on someone's grave",
	"Dancing squid",
	"Dark matter",
	"Darth Vader's day job",
	"Death by salmon",
	"Desert igloo",
	"Disappointing gravestones",
	"Dogs dressed as humans",
	"Dolphins invade the land",
	"Dr. Horse",
	"Dragon hatching out of an Easter egg",
	"Dreaming of bacon",
	"Drooling in your sleep",
	"Drowning in someone's eye",
	"Drunk fly",
	"Eating roadkill",
	"Eating spiderwebs",
	"Eating the largest potato",
	"Eels, Eels, and more eels",
	"Elephant with wheels",
	"Embarrassing x-ray",
	"Evil goose",
	"Exploding cuckoo clock",
	"Eye-wateringly strong pickles",
	"Eyeball golf",
	"Eyeballs for teeth",
	"Face-plant",
	"Fainting goats",
	"Falling apart",
	"Fear of toilets",
	"Fighting fire with fire",
	"First contact with the Martians",
	"Fishing for compliments",
	"Flamingo city",
	"Florida Man",
	"Flying submarine",
	"Flying toaster",
	"Foam party",
	"Forest of lasers",
	"Forgetting how to eat",
	"Freak show",
	"Freestyle kazoo solo",
	"Freezing your own head",
	"Frisbee decapitation",
	"Frog on a unicycle",
	"Gandhi magician",
	"Gastric band",
	"Ginger Lickin' Good!",
	"Giraffe limbo contest",
	"Glued to the screen",
	"God gives you limes",
	"Going out in a blaze of glory",
	"Going to your own house on google street view",
	"Googling your own name",
	"Gorilla panic",
	"Half deer half bee",
	"Harry Potter baby with a gun",
	"Haunted Oven",
	"Heaving breathing",
	"Holding in Hell",
	"I.T. rage",
	"Inspector Potato",
	"Invisible iguana",
	"Jazz hands",
	"Jealous camel",
	"Jesus showing of his sick yoyo skills",
	"Juggling the planets",
	"Jumping out of your skin",
	"Karate chopping a frog",
	"Killing two birds with one stone",
	"Knight in shining armour",
	"LARPing",
	"Lactose intolerance",
	"Laughing horse",
	"Laughing your head off",
	"Lego man steps on lego",
	"Licking a cactus",
	"Licking people's shoes",
	"Life giving you lemons",
	"Lion hailing a taxi",
	"Living in a skip",
	"Lost in IKEA",
	"Lost in a ball pit",
	"Luigi in Mario's clothes",
	"Making a bald-headed man cry",
	"Making an arse out of yourself",
	"Making an onion cry",
	"Map of thw world",
	"Meat sweats",
	"Melon boxing match",
	"Minesweeping",
	"Mobility scooter hit and run",
	"Monkey business",
	"Monkey knife fight",
	"Monkey with a gun",
	"Monopoly man hates capitalism",
	"Moth with a human face",
	"Mr. Floppy",
	"Muffin top",
	"Neckbeard",
	"Octopus mating season",
	"Olympic tiddlywinks",
	"Oompa Loompas conquering the world",
	"Owl eating an orange",
	"Parrot with laser eyes",
	"Pathetic snowman",
	"Penguin astronaut",
	"Personal space invasion",
	"Pet Turkey",
	"Pet rock",
	"Pie eating contest gone wrong",
	"Pipe organ solo",
	"Playing darts with pens",
	"Playing the drums with bananas",
	"Popcorn surprise",
	"Potty mouth",
	"Pulling a hat out of a rabbit",
	"Putting make-up on an owl",
	"Questionable parenting",
	"Raised by squirrels",
	"Racoon burglar",
	"Rat janitor",
	"Raven in a lava lamp",
	"Really ugly baby",
	"Riding a weasel",
	"Rubbernecking",
	"Running away from your problems",
	"Running someone up the wrong way",
	"Santa's bad cooking",
	"Sausage fingers",
	"School bus for schools",
	"Seeing a man about a horse",
	"Self-portrait (you, in the morning)",
	"Sharknado",
	"Shaving a llama",
	"Shotgun wedding",
	"Shouting at old people",
	"Shrimp with muscular legs",
	"Singing armadillo",
	"Skeleton in your closet",
	"Skiing anteater",
	"Slow day at the box factory",
	"Snail jockey",
	"Snake with a hat",
	"Sore loser",
	"Space madness",
	"Space taco",
	"Spontaneous human combustion",
	"Spooning a spoon",
	"Squid playing the saxophone in outer space",
	"Stamping on child's sandcastle",
	"Starfish diffusing a bomb",
	"Staring contest",
	"Stealing someone's thunder",
	"Stealing the covers",
	"Stranger danger!",
	"Stretchy manatee",
	"Stud muffin",
	"Suitcase aquarium",
	"T-Rex with a brand new handbag",
	"Taking baby from a candy",
	"Tasering a sloth",
	"Teletubbies forming a cult",
	"Tentacle handshake",
	"Terrified by butter",
	"The Eiffel Tower is the Eye of Sauron",
	"The Fork Museum",
	"The Heimlich maneuver",
	"The Moon running away from home",
	"The Queen on a trampoline",
	"The Trump Family",
	"The blind leading the blind",
	"The duck face",
	"The happiest caterpillar of them all",
	"The longest of beards",
	"The reason I'm single",
	"The starry night",
	"The tallest burger",
	"The ugly friend",
	"The wispiest of moustaches",
	"The world's biggest sneeze",
	"Three octopus hugging",
	"Throwing salt over your shoulder",
	"Throwing the baby out with the bathwater",
	"Tickle a pickle",
	"Toddler beauty pageant",
	"Toenail fungus",
	"Tokyo Tower",
	"Too much acid",
	"Toucan lost it's beak",
	"Trapped in a phone box",
	"Trimming your neighbour's bush",
	"Trust exercises",
	"Unicorn meets Star Wars",
	"Unicorn rainbow fart",
	"Using a Banana for scale",
	"Vampire eating garlic",
	"Velociraptor Jesus",
	"Very buff toad",
	"Walking into a mirror",
	"Wandering hands",
	"Washing someone's mouth out with soap",
	"Weasel befriends an otter",
	"Wet handshake",
	"What really happened to the dinosaurs",
	"Wheelbarrow race",
	"Who let the dogs out",
	"Winnie the Pooh eating a pineapple",
	"Wiping the smile off your face",
	"Wolf disguised as a flower",
	"Woman with shell for a hat",
	"Worm God",
	"Writing a book under a tree",
	"You scratch my back, I'll scratch yours",
	"Your vegetable friend",
	"\"Kitten Mittens\"",
]