module.exports = [
	"A bad haircut",
	"A bizarre gardening accident",
	"A loving pat on the head",
	"A man hiding in a pram",
	"A very disappointing Christmas",
	"Abducted by butterflies",
	"Adopting a cacus",
	"Amoeba disco",
	"An unfortunate birthmark",
	"Angry barbecue",
	"Awkward family photo",
	"Awkward hug",
	"Aztec sacrifice",
	"Back acne",
	"Bad babysitter",
	"Badly drawn on eyebrows",
	"Badly trained dentist",
	"Beating around the bush",
	"Beating up a jellyfish",
	"Beer goggles",
	"Big girl's blouse",
	"Bingo wings",
	"Biting off more than you can chew",
	"Brain freeze",
	"Brushing your tongue",
	"Bunny boiler",
	"Butt chin",
	"Butt dial",
	"Cannibal finger buffet",
	"Cat got you tongue",
	"Centaur lolipop man",
	"Cereal killer",
	"Cheese nightmare",
	"Choking on doughnuts",
	"Cleaning out your pipes",
	"Clown police line-up",
	"Combing your hair with hedgehog",
	"Costing an arm and a leg",
	"Cow tipping",
	"Cowboy wrestling",
	"Crap parkour",
	"Crying on the inside",
	"Crying over spilt milk",
	"Crying yourself to sleep",
	"Dad dancing",
	"Dancing on someone's grave",
	"Dark matter",
	"Darth Vader's day job",
	"Death by salmon",
	"Desert igloo",
	"Disappointing gravestones",
	"Dogs dressed as humans",
	"Dreaming of bacon",
	"Drooling in your sleep",
	"Drowning in someone's eye",
	"Drunk fly",
	"Eating roadkill",
	"Eating spiderwebs",
	"Eels, Eels, and more eels",
	"Embarrassing x-ray",
	"Exploding cuckoo clock",
	"Eye-wateringly strong pickles",
	"Eyeball golf",
	"Face-plant",
	"Fainting goats",
	"Falling apart",
	"Fear of toilets",
	"Fighting fire with fire",
	"Florida Man",
	"Foam party",
	"Forgetting how to eat",
	"Freak show",
	"Freestyle kazoo solo",
	"Freezing your own head",
	"Frisbee decapitation",
	"Gastric band",
	"Ginger Lickin' Good!",
	"Giraffe limbo contest",
	"Glued to the screen",
	"Going out in a blaze of glory",
	"Gorilla panic",
	"Haunted Oven",
	"Heaving breathing",
	"Holding in Hell",
	"I.T. rage",
	"Jazz hands",
	"Jumping out of your skin",
	"Karate chopping a frog",
	"Killing two birds with one stone",
	"LARPing",
	"Lactose intolerance",
	"Laughing horse",
	"Laughing your head off",
	"Licking people's shoes",
	"Life giving you lemons",
	"Living in a skip",
	"Lost in IKEA",
	"Lost in a ball pit",
	"Making a bald-headed man cry",
	"Making an arse out of yourself",
	"Making an onion cry",
	"Meat sweats",
	"Minesweeping",
	"Mobility scooter hit and run",
	"Monkey business",
	"Monkey knife fight",
	"Monkey with a gun",
	"Mr. Floppy",
	"Muffin top",
	"Neckbeard",
	"Octopus mating season",
	"Pathetic snowman",
	"Penguin astronaut",
	"Personal space invasion",
	"Pet rock",
	"Playing the drums with bananas",
	"Popcorn surprise",
	"Potty mouth",
	"Pulling a hat out of a rabbit",
	"Putting make-up on an owl",
	"Questionable parenting",
	"Raised by squirrels",
	"Really ugly baby",
	"Riding a weasel",
	"Rubbernecking",
	"Running away from your problems",
	"Running someone up the wrong way",
	"Sausage fingers",
	"Seeing a man about a horse",
	"Self-portrait (you, in the morning)",
	"Sharknado",
	"Shaving a llama",
	"Shotgun wedding",
	"Shouting at old people",
	"Skeleton in your closet",
	"Slow day at the box factory",
	"Snail jockey",
	"Sore loser",
	"Spontaneous human combustion",
	"Spooning a spoon",
	"Stamping on child's sandcastle",
	"Staring contest",
	"Stealing someone's thunder",
	"Stealing the covers",
	"Stranger danger!",
	"Stud muffin",
	"Suitcase aquarium",
	"T-Rex with a brand new handbag",
	"Taking baby from a candy",
	"Tasering a sloth",
	"Terrified by butter",
	"The Fork Museum",
	"The Heimlich maneuver",
	"The Trump Family",
	"The blind leading the blind",
	"The duck face",
	"The reason I'm single",
	"The ugly friend",
	"The wispiest of moustaches",
	"The world's biggest sneeze",
	"Throwing the baby out with the bathwater",
	"Tickle a pickle",
	"Toddler beauty pageant",
	"Toenail fungus",
	"Too much acid",
	"Trapped in a phone box",
	"Trimming your neighbour's bush",
	"Trust exercises",
	"Unicorn rainbow fart",
	"Velociraptor Jesus",
	"Walking into a mirror",
	"Wandering hands",
	"Washing someone's mouth out with soap",
	"Wet handshake",
	"What really happened to the dinosaurs",
	"Wheelbarrow race",
	"Wiping the smile off your face",
	"Worm God",
	"You scratch my back, I'll scratch yours",
	"Your vegetable friend",
	"\"Kitten Mittens\"",
]