module.exports = [
	"A bad cosplay",
	"Akira",
	"Angel's Egg",
	"Anime youtubers",
	"Attack on Titan",
	"Best boy",
	"Best girl",
	"Brushing your sister's teeth",
	"Bunny girl",
	"Clannad",
	"Cute girls doing cute things",
	"Death Note",
	"Doki doki",
	"Evangelion",
	"FLCL",
	"Fanservice",
	"Invisible parents",
	"It was me, Dio!",
	"It's over 9000!",
	"Jojo pose",
	"Late for school with toast in mouth",
	"Loli police",
	"Magical girls",
	"Maid Cafe",
	"Naruto run",
	"Nice boat",
	"One Punch Man",
	"Onii-Chan",
	"Oppai",
	"Pokemon",
	"Rem",
	"School days",
	"Senpai",
	"Serial Experiments Lain",
	"Sword Art Online",
	"Tournament arc",
	"Tsundere",
	"Vocaloid",
	"Vtuber simp",
	"Worst girl",
	"Yandere",
	"uwu",
]