module.exports = [
	"Worm God",
	"Minesweeping",
	"Badly drawn on eyebrows",
	"Toddler beauty pageant",
	"Heaving breathing",
	"Brushing your tongue",
	"Jumping out of your skin",
	"Back acne",
	"Embarrassing x-ray",
	"Dreaming of bacon",
	"Freestyle kazoo solo",
	"Stud muffin",
	"The Trump Family",
	"Bum bongos",
	"Getting fingered by the law",
	"What really happened to the dinosaurs",
	"Dark matter",
	"Amoeba disco",
	"Tickle a pickle",
	"Crap parkour",
	"T-Rex with a brand new handbag",
	"Polishing a turd",
	"Beating up a jellyfish",
	"Slow day at the box factory",
	"Unicorn rainbow fart",
	"Eyeball golf",
	"Bronies",
	"Abducted by butterflies",
	"Suitcase aquarium",
	"Cream pie",
	"Gorilla panic",
	"Shouting at old people",
	"Spontaneous human combustion",
	"I.T. rage",
	"Spooning a spoon",
	"Dad dancing",
	"Pathetic snowman",
	"Drunk fly",
	"Big girl's blouse",
	"Packing a sausage",
	"Joyless sex",
	"Questionable parenting",
	"A man hiding in a pram",
	"Staring contest",
	"Meat sweats",
	"1950's Sex Ed poster",
	"The blind leading the blind",
	"Stamping on child's sandcastle",
	"Killing two birds with one stone",
	"Naked statue of yourself",
	"Moobs",
	"Shaving a llama",
	"Lactose intolerance",
	"Beer goggles",
	"Dry humping",
	"Booty call",
	"Octopus mating season",
	"Too much acid",
	"Alcoholic house husband",
	"Costing an arm and a leg",
]