module.exports = [
	"Fear of toilets",
	"Frisbee decapitation",
	"Armpit fetish",
	"Muffin top",
	"Raised by squirrels",
	"Brain freeze",
	"Washing someone's mouth out with soap",
	"Making a bald-headed man cry",
	"Adopting a cacus",
	"Sharknado",
	"Crying over spilt milk",
	"Toenail fungus",
	"Monkey knife fight",
	"It was me, Dio!",
	"Bangkok Ping Pong Show",
	"life giving you lemons",
	"Eye-wateringly strong pickles",
	"Side boob",
	"An unfortunate birthmark",
	"Stealing someone's thunder",
	"Friendly camel toe",
	"Cat got you tongue",
	"The ugly friend",
	"Stranger danger!",
	"Disappointing gravestones",
	"Eating roadkill",
	"Snail jockey",
	"Centaur lolipop man",
	"Racist grandma",
	"Mobility scooter hit and run",
	"Butt chin",
	"Walking into a mirror",
	"The Fork Museum",
	"Edible panties",
	"Combing your hair with hedgehog",
	"Choking on doughnuts",
	"Sore loser",
	"Banana hammock",
	"Pet rock",
	"Monkey business",
	"Going at it like rabbits",
	"Biting off more than you can chew",
	"Running someone up the wrong way",
	"Badly trained dentist",
	"Clown police line-up",
	"Extreme breastfeeding",
	"S.T.D. Appreciation Day",
	"Beating around the bush",
	"Popcorn surprise",
	"Aztec sacrifice",
	"Personal space invasion",
	"The wispiest of moustaches",
	"Going out in a blaze of glory",
	"Dogs dressed as humans",
	"Stealing the covers",
	"Eels, Eels, and more eels",
	"Trimming your neighbour's bush",
	"A very disappointing Christmas",
	"Eating spiderwebs",
	"Trapped in a phone box",
]